"""add question set assessment configuration

Revision ID: 1827d6235b05
Revises: 43a84d3cb3fb
Create Date: 2026-09-23 22:00:53.840962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1827d6235b05'
down_revision: Union[str, Sequence[str], None] = '43a84d3cb3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_set_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_set_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('candidate_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_set_configurations_id'), 'question_set_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_question_set_configurations_question_set_id'), 'question_set_configurations', ['question_set_id'], unique=True)
    op.add_column('jobs', sa.Column('experience_required', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'experience_required')
    op.drop_index(op.f('ix_question_set_configurations_question_set_id'), table_name='question_set_configurations')
    op.drop_index(op.f('ix_question_set_configurations_id'), table_name='question_set_configurations')
    op.drop_table('question_set_configurations')
    # ### end Alembic commands ###
