"""add question review audit fields

Revision ID: 3f0e4f7ef404
Revises: c2f90577f4d6
Create Date: 2026-09-23 23:50:16.618186
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f0e4f7ef404"
down_revision: Union[str, Sequence[str], None] = "c2f90577f4d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.add_column(
        "questions",
        sa.Column(
            "reviewed_by",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.add_column(
        "questions",
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_questions_created_by"),
        "questions",
        ["created_by"],
        unique=False,
    )

    op.create_index(
        op.f("ix_questions_reviewed_by"),
        "questions",
        ["reviewed_by"],
        unique=False,
    )

    op.create_foreign_key(
        "questions_created_by_fkey",
        "questions",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_foreign_key(
        "questions_reviewed_by_fkey",
        "questions",
        "users",
        ["reviewed_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "questions_reviewed_by_fkey",
        "questions",
        type_="foreignkey",
    )

    op.drop_constraint(
        "questions_created_by_fkey",
        "questions",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_questions_reviewed_by"),
        table_name="questions",
    )

    op.drop_index(
        op.f("ix_questions_created_by"),
        table_name="questions",
    )

    op.drop_column(
        "questions",
        "reviewed_at",
    )

    op.drop_column(
        "questions",
        "reviewed_by",
    )

    op.drop_column(
        "questions",
        "created_by",
    )

    # ### end Alembic commands ###