"""create question sections

Revision ID: 43a84d3cb3fb
Revises: 754d9290569d
Create Date: 2026-09-23 20:50:03.186224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a84d3cb3fb'
down_revision: Union[str, Sequence[str], None] = '754d9290569d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'section_id', name='uq_question_section')
    )
    op.create_index(op.f('ix_question_sections_id'), 'question_sections', ['id'], unique=False)
    op.create_index(op.f('ix_question_sections_question_id'), 'question_sections', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_sections_section_id'), 'question_sections', ['section_id'], unique=False)
    op.create_index(op.f('ix_questions_source'), 'questions', ['source'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_source'), table_name='questions')
    op.drop_index(op.f('ix_question_sections_section_id'), table_name='question_sections')
    op.drop_index(op.f('ix_question_sections_question_id'), table_name='question_sections')
    op.drop_index(op.f('ix_question_sections_id'), table_name='question_sections')
    op.drop_table('question_sections')
    # ### end Alembic commands ###
