"""add job assessment access

Revision ID: d7306794fe33
Revises: 3f0e4f7ef404
Create Date: 2026-09-24 01:46:35.199112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7306794fe33'
down_revision: Union[str, Sequence[str], None] = '3f0e4f7ef404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_assessment_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', name='uq_job_assessment_access_job_user')
    )
    op.create_index(op.f('ix_job_assessment_access_assigned_by'), 'job_assessment_access', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_job_assessment_access_id'), 'job_assessment_access', ['id'], unique=False)
    op.create_index(op.f('ix_job_assessment_access_job_id'), 'job_assessment_access', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_assessment_access_user_id'), 'job_assessment_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_assessment_access_user_id'), table_name='job_assessment_access')
    op.drop_index(op.f('ix_job_assessment_access_job_id'), table_name='job_assessment_access')
    op.drop_index(op.f('ix_job_assessment_access_id'), table_name='job_assessment_access')
    op.drop_index(op.f('ix_job_assessment_access_assigned_by'), table_name='job_assessment_access')
    op.drop_table('job_assessment_access')
    # ### end Alembic commands ###
